apiVersion: v1
kind: Service
metadata:
  name: jenkinsweb-nginx-service-1
  labels:
    app: jenkinsweb-nginx-1
spec:
  type: LoadBalancer
  selector:
    app: jenkinsweb-nginx-1
  ports:
    - port: 80
      targetPort: 80
